version: '3'
services:
  express-api:
    build: .
    ports:
      - "3089:3089"
    volumes:
      - .:/usr/src/app  # Mount folder lokal ke dalam container
    environment:
      NODE_ENV: development